---
version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pytodo:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres
